name: ins_dup
description: Instagram duplication

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase相關
  firebase_core: ^1.19.2
  # Bloc
  bloc: ^8.1.0
  flutter_bloc: ^8.0.1
  # Dependency Injection
  get_it: ^7.2.0
  # Database
  objectbox: ^1.6.0
  objectbox_flutter_libs: any
  shared_preferences: ^2.0.15
  # 權限許可
  permission_handler: ^10.0.0
  # RESTFUL api
  http: ^0.13.4
  # 其他
  rxdart: ^0.27.5
  equatable: ^2.0.5
  dartz: ^0.10.1
  cupertino_icons: ^1.0.2
  go_router: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  objectbox_generator: any

  flutter_lints: ^2.0.0

objectbox:
  output_dir: core/packages/objectbox

flutter:
  uses-material-design: true
